name: NPM

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Set up Go
        uses: actions/setup-go@master
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@master

      - uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: |
          npm install
          npm run install:protoc

      - name: Generate gRPC Stubs
        run: npm run generate

      - name: Test
        run: npm test

  pack:
    name: Pack
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up Go
        uses: actions/setup-go@master
        id: go

      - name: Install Protoc
        uses: arduino/setup-protoc@master
      - name: Install Protoc 3rd party protos
        run: npm run install:protoc

      - name: Install Dependencies
        run: npm install

      - name: Generate Version
        run: ./scripts/generate-version.sh

      - name: Pack Testing
        run: ./scripts/npm-pack-testing.sh

  publish:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/v'))
    name: Publish
    needs: [build, pack]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Protoc
        uses: arduino/setup-protoc@master
      - name: Install Protoc 3rd party protos
        run: npm run install:protoc

      - name: Install Dependencies
        run: npm install
      - name: Generate Version
        run: ./scripts/generate-version.sh
      - name: Set Publish Config
        run: ./scripts/package-publish-config-tag.sh
      - run: npm run dist

      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.ref }} =~ ^refs/heads/(master|v[0-9]+\.[0-9]+.*)$ ]]; then
              echo ::set-output name=match::true
          fi  # See: https://stackoverflow.com/a/58869470/1123955
      - name: Is A Publish Branch
        if: steps.check-branch.outputs.match == 'true'
        run: |
          NAME=$(npx pkg-jq -r .name)
          VERSION=$(npx pkg-jq -r .version)
          if npx version-exists "$NAME" "$VERSION"
          then echo "$NAME@$VERSION exists on NPM, skipped."
          else npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Is Not A Publish Branch
        if: steps.check-branch.outputs.match != 'true'
        run: echo 'Not A Publish Branch'
